/// <reference lib="webworker" />

// See https://developer.chrome.com/docs/workbox/modules/
// for the list of available Workbox modules.

import { clientsClaim } from "workbox-core";
import { ExpirationPlugin } from "workbox-expiration";
import {
  precacheAndRoute,
  createHandlerBoundToURL,
  matchPrecache,
} from "workbox-precaching";
import { registerRoute, setCatchHandler } from "workbox-routing";
import { CacheFirst, StaleWhileRevalidate } from "workbox-strategies";
import { googleFontsCache, imageCache } from "workbox-recipes";
import defaultComponentImage from "./images/componentDefault.png";

declare const self: ServiceWorkerGlobalScope;

clientsClaim();

// Precache all of the assets generated by the build process.
// Their URLs are injected into the manifest variable below.
precacheAndRoute(self.__WB_MANIFEST);

// Send all navigation requests to index.html
const fileExtensionRegexp = /\/[^/?]+\.[^/]+$/;
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== "navigate") {
      return false;
    }

    // If this is a URL that starts with /_, skip.
    if (url.pathname.startsWith("/_")) {
      return false;
    }

    // If this looks like a URL for a resource, because it contains a file extension, skip.
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    }

    // Return true to signal that we want to use the handler.
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + "/index.html")
);

// Handle caching the translations
registerRoute(
  ({ url }) =>
    url.origin === self.location.origin &&
    url.pathname.startsWith(process.env.PUBLIC_URL + "/locales/"),
  // Serve cached translation, then immediately update the cache in the background
  new StaleWhileRevalidate({
    cacheName: "translations",
    // Limit how many translations can be cached, as we don't expect the user to be switching between lots of them
    plugins: [new ExpirationPlugin({ maxEntries: 10 })],
  })
);

// Handle caching the page font
googleFontsCache();

// Helper function for determining if a given URL is for a component image
const isComponentImage = (url: URL) =>
  url.origin === self.location.origin &&
  [
    "boxes",
    "buildings",
    "cards",
    "landmarks",
    "maps",
    "meeples",
    "tokens",
  ].some((path) =>
    url.pathname.startsWith(process.env.PUBLIC_URL + "/images/" + path + "/")
  );

// Handle caching the component images (which live outside of the build)
registerRoute(
  ({ url }) => isComponentImage(url),
  // Always serve cached image, only making a network request on cache miss
  new CacheFirst({
    cacheName: "componentImages",
    plugins: [
      // We set a 30 day cache length on the images rather than a max entries, as we expect a lot of them
      new ExpirationPlugin({
        maxAgeSeconds: 30 * 24 * 60 * 60,
        // Since the images are just for decoration, nominate them to be cleared first when the cache fills
        purgeOnQuotaError: true,
      }),
    ],
  })
);

// Handle caching any other images
imageCache();

// Handle fallbacks
setCatchHandler(async ({ url }) => {
  // Ensure that component images that are not cached can be replaced with a fallback when offline
  if (isComponentImage(url)) {
    return (await matchPrecache(defaultComponentImage)) || Response.error();
  }

  return Response.error();
});

// This allows the web app to trigger skipWaiting via registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});
